// Initial supplier data
export const initialSuppliers = [
  // Pending Suppliers
  {
    id: 1,
    name: "Kamal Perera",
    nic: "952847393V",
    phone: "+94 77 123 4567",
    location: "Maharagama, Colombo",
    supply: "500 kg",
    date: "2025-06-08",
    approvedDate: null,
    rejectedDate: null,
    rejectionReason: null,
    status: "pending",
    email: "kamal@email.com",
    businessType: "Individual Farmer",
    experience: "5 years",
    priority: "medium",
    supplierId: null,
    route: null,
  },
  {
    id: 2,
    name: "Nimal Silva",
    nic: "891234567V",
    phone: "+94 71 987 6543",
    location: "Kegalle, Sabaragamuwa",
    supply: "750 kg",
    date: "2025-06-07",
    approvedDate: null,
    rejectedDate: null,
    rejectionReason: null,
    status: "pending",
    email: "nimal.silva@email.com",
    businessType: "Cooperative",
    experience: "10 years",
    priority: "high",
    supplierId: null,
    route: null,
  },
  {
    id: 5,
    name: "Amara Wickramasinghe",
    nic: "881234567V",
    phone: "+94 78 456 7890",
    location: "Ratnapura, Sabaragamuwa",
    supply: "600 kg",
    date: "2025-06-15",
    approvedDate: null,
    rejectedDate: null,
    rejectionReason: null,
    status: "pending",
    email: "amara.w@email.com",
    businessType: "Family Farm",
    experience: "8 years",
    priority: "medium",
    supplierId: null,
    route: null,
  },
  // Approved Suppliers
  {
    id: 3,
    name: "Sunil Jayawardena",
    nic: "751234567V",
    phone: "+94 76 555 1234",
    location: "Kandy, Central",
    supply: "300 kg",
    date: "2025-06-05",
    approvedDate: "2025-06-10",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "sunil.j@email.com",
    businessType: "Individual Farmer",
    experience: "3 years",
    priority: "low",
    supplierId: "SUP-2025-003",
    route: "Route A-01 (Colombo North)",
  },
  {
    id: 6,
    name: "Chamari Fernando",
    nic: "821234567V",
    phone: "+94 75 123 4567",
    location: "Nuwara Eliya, Central",
    supply: "800 kg",
    date: "2025-05-28",
    approvedDate: "2025-06-02",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "chamari.f@email.com",
    businessType: "Cooperative",
    experience: "12 years",
    priority: "high",
    supplierId: "SUP-2025-006",
    route: "Route B-02 (Central Hills)",
  },
  {
    id: 7,
    name: "Ruwan Kumara",
    nic: "791234567V",
    phone: "+94 77 987 6543",
    location: "Badulla, Uva",
    supply: "400 kg",
    date: "2025-05-25",
    approvedDate: "2025-05-30",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "ruwan.k@email.com",
    businessType: "Individual Farmer",
    experience: "6 years",
    priority: "medium",
    supplierId: "SUP-2025-007",
    route: "Route C-03 (Uva Province)",
  },
  {
    id: 8,
    name: "Sanduni Rajapaksa",
    nic: "831234567V",
    phone: "+94 76 234 5678",
    location: "Hatton, Central",
    supply: "650 kg",
    date: "2025-05-20",
    approvedDate: "2025-05-25",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "sanduni.r@email.com",
    businessType: "Family Farm",
    experience: "9 years",
    priority: "high",
    supplierId: "SUP-2025-008",
    route: "Route B-02 (Central Hills)",
  },
  // Rejected Suppliers
  {
    id: 4,
    name: "Priya Mendis",
    nic: "754567890V",
    phone: "+94 77 234 5678",
    location: "Galle, Southern",
    supply: "450 kg",
    date: "2025-06-04",
    approvedDate: null,
    rejectedDate: "2025-06-12",
    rejectionReason:
      "Insufficient land documentation and location too far from collection points.",
    status: "rejected",
    email: "priya.mendis@email.com",
    businessType: "Individual Farmer",
    experience: "2 years",
    priority: "low",
    supplierId: null,
    route: null,
  },
  {
    id: 9,
    name: "Lakmal Dissanayake",
    nic: "771234567V",
    phone: "+94 78 345 6789",
    location: "Hambantota, Southern",
    supply: "200 kg",
    date: "2025-06-01",
    approvedDate: null,
    rejectedDate: "2025-06-08",
    rejectionReason:
      "Tea quality samples did not meet factory standards. Requires improvement in cultivation practices.",
    status: "rejected",
    email: "lakmal.d@email.com",
    businessType: "Individual Farmer",
    experience: "1 year",
    priority: "low",
    supplierId: null,
    route: null,
  },
  {
    id: 10,
    name: "Tharaka Bandara",
    nic: "801234567V",
    phone: "+94 71 456 7890",
    location: "Matara, Southern",
    supply: "350 kg",
    date: "2025-05-30",
    approvedDate: null,
    rejectedDate: "2025-06-05",
    rejectionReason:
      "Unable to verify land ownership documents and transportation logistics not feasible.",
    status: "rejected",
    email: "tharaka.b@email.com",
    businessType: "Individual Farmer",
    experience: "4 years",
    priority: "medium",
    supplierId: null,
    route: null,
  },
  // Additional Approved Suppliers (11-30)
  {
    id: 11,
    name: "Dilshan Perera",
    nic: "851234567V",
    phone: "+94 77 111 2222",
    location: "Matale, Central",
    supply: "720 kg",
    date: "2025-05-15",
    approvedDate: "2025-05-20",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "dilshan.p@email.com",
    businessType: "Cooperative",
    experience: "15 years",
    priority: "high",
    supplierId: "SUP-2025-011",
    route: "Route A-01 (Colombo North)",
  },
  {
    id: 12,
    name: "Malini Jayasekara",
    nic: "741234567V",
    phone: "+94 76 222 3333",
    location: "Dambulla, Central",
    supply: "480 kg",
    date: "2025-05-12",
    approvedDate: "2025-05-18",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "malini.j@email.com",
    businessType: "Family Farm",
    experience: "7 years",
    priority: "medium",
    supplierId: "SUP-2025-012",
    route: "Route B-02 (Central Hills)",
  },
  {
    id: 13,
    name: "Asanka Fernando",
    nic: "861234567V",
    phone: "+94 78 333 4444",
    location: "Bandarawela, Uva",
    supply: "590 kg",
    date: "2025-05-10",
    approvedDate: "2025-05-16",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "asanka.f@email.com",
    businessType: "Individual Farmer",
    experience: "11 years",
    priority: "high",
    supplierId: "SUP-2025-013",
    route: "Route C-03 (Uva Province)",
  },
  {
    id: 14,
    name: "Kavitha Rathnayake",
    nic: "731234567V",
    phone: "+94 75 444 5555",
    location: "Gampola, Central",
    supply: "670 kg",
    date: "2025-05-08",
    approvedDate: "2025-05-14",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "kavitha.r@email.com",
    businessType: "Cooperative",
    experience: "13 years",
    priority: "high",
    supplierId: "SUP-2025-014",
    route: "Route B-02 (Central Hills)",
  },
  {
    id: 15,
    name: "Jagath Silva",
    nic: "721234567V",
    phone: "+94 77 555 6666",
    location: "Haputale, Uva",
    supply: "380 kg",
    date: "2025-05-05",
    approvedDate: "2025-05-12",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "jagath.s@email.com",
    businessType: "Individual Farmer",
    experience: "8 years",
    priority: "medium",
    supplierId: "SUP-2025-015",
    route: "Route C-03 (Uva Province)",
  },
  {
    id: 16,
    name: "Saman Wickramasinghe",
    nic: "811234567V",
    phone: "+94 76 666 7777",
    location: "Talawakelle, Central",
    supply: "750 kg",
    date: "2025-05-03",
    approvedDate: "2025-05-10",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "saman.w@email.com",
    businessType: "Family Farm",
    experience: "16 years",
    priority: "high",
    supplierId: "SUP-2025-016",
    route: "Route B-02 (Central Hills)",
  },
  {
    id: 17,
    name: "Nimali Gunasekara",
    nic: "841234567V",
    phone: "+94 78 777 8888",
    location: "Walapane, Central",
    supply: "520 kg",
    date: "2025-05-01",
    approvedDate: "2025-05-08",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "nimali.g@email.com",
    businessType: "Individual Farmer",
    experience: "9 years",
    priority: "medium",
    supplierId: "SUP-2025-017",
    route: "Route B-02 (Central Hills)",
  },
  {
    id: 18,
    name: "Rajitha Kumara",
    nic: "701234567V",
    phone: "+94 75 888 9999",
    location: "Welimada, Uva",
    supply: "430 kg",
    date: "2025-04-28",
    approvedDate: "2025-05-05",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "rajitha.k@email.com",
    businessType: "Cooperative",
    experience: "14 years",
    priority: "high",
    supplierId: "SUP-2025-018",
    route: "Route C-03 (Uva Province)",
  },
  {
    id: 19,
    name: "Chathura Perera",
    nic: "871234567V",
    phone: "+94 77 999 0000",
    location: "Nawalapitiya, Central",
    supply: "610 kg",
    date: "2025-04-25",
    approvedDate: "2025-05-02",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "chathura.p@email.com",
    businessType: "Family Farm",
    experience: "10 years",
    priority: "medium",
    supplierId: "SUP-2025-019",
    route: "Route A-01 (Colombo North)",
  },
  {
    id: 20,
    name: "Indika Jayawardena",
    nic: "761234567V",
    phone: "+94 76 000 1111",
    location: "Maskeliya, Central",
    supply: "780 kg",
    date: "2025-04-22",
    approvedDate: "2025-04-30",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "indika.j@email.com",
    businessType: "Individual Farmer",
    experience: "12 years",
    priority: "high",
    supplierId: "SUP-2025-020",
    route: "Route B-02 (Central Hills)",
  },
  // Additional Pending Suppliers (21-35)
  {
    id: 21,
    name: "Mahinda Rathnayake",
    nic: "681234567V",
    phone: "+94 78 111 2222",
    location: "Ampara, Eastern",
    supply: "450 kg",
    date: "2025-06-20",
    approvedDate: null,
    rejectedDate: null,
    rejectionReason: null,
    status: "pending",
    email: "mahinda.r@email.com",
    businessType: "Individual Farmer",
    experience: "6 years",
    priority: "medium",
    supplierId: null,
    route: null,
  },
  {
    id: 22,
    name: "Wasantha Silva",
    nic: "691234567V",
    phone: "+94 75 222 3333",
    location: "Polonnaruwa, North Central",
    supply: "680 kg",
    date: "2025-06-18",
    approvedDate: null,
    rejectedDate: null,
    rejectionReason: null,
    status: "pending",
    email: "wasantha.s@email.com",
    businessType: "Cooperative",
    experience: "11 years",
    priority: "high",
    supplierId: null,
    route: null,
  },
  {
    id: 23,
    name: "Kumari Fernando",
    nic: "821234568V",
    phone: "+94 77 333 4444",
    location: "Anuradhapura, North Central",
    supply: "390 kg",
    date: "2025-06-16",
    approvedDate: null,
    rejectedDate: null,
    rejectionReason: null,
    status: "pending",
    email: "kumari.f@email.com",
    businessType: "Family Farm",
    experience: "7 years",
    priority: "medium",
    supplierId: null,
    route: null,
  },
  {
    id: 24,
    name: "Pradeep Wijesinghe",
    nic: "751234568V",
    phone: "+94 76 444 5555",
    location: "Kurunegala, North Western",
    supply: "570 kg",
    date: "2025-06-14",
    approvedDate: null,
    rejectedDate: null,
    rejectionReason: null,
    status: "pending",
    email: "pradeep.w@email.com",
    businessType: "Individual Farmer",
    experience: "9 years",
    priority: "high",
    supplierId: null,
    route: null,
  },
  {
    id: 25,
    name: "Sandya Mendis",
    nic: "831234568V",
    phone: "+94 78 555 6666",
    location: "Puttalam, North Western",
    supply: "320 kg",
    date: "2025-06-12",
    approvedDate: null,
    rejectedDate: null,
    rejectionReason: null,
    status: "pending",
    email: "sandya.m@email.com",
    businessType: "Family Farm",
    experience: "5 years",
    priority: "low",
    supplierId: null,
    route: null,
  },
  {
    id: 26,
    name: "Thilak Perera",
    nic: "771234568V",
    phone: "+94 75 666 7777",
    location: "Chilaw, North Western",
    supply: "490 kg",
    date: "2025-06-10",
    approvedDate: null,
    rejectedDate: null,
    rejectionReason: null,
    status: "pending",
    email: "thilak.p@email.com",
    businessType: "Cooperative",
    experience: "13 years",
    priority: "medium",
    supplierId: null,
    route: null,
  },
  {
    id: 27,
    name: "Chaminda Jayasuriya",
    nic: "661234567V",
    phone: "+94 77 777 8888",
    location: "Matugama, Western",
    supply: "640 kg",
    date: "2025-06-08",
    approvedDate: null,
    rejectedDate: null,
    rejectionReason: null,
    status: "pending",
    email: "chaminda.j@email.com",
    businessType: "Individual Farmer",
    experience: "8 years",
    priority: "high",
    supplierId: null,
    route: null,
  },
  {
    id: 28,
    name: "Renuka Dissanayake",
    nic: "741234568V",
    phone: "+94 76 888 9999",
    location: "Kalutara, Western",
    supply: "360 kg",
    date: "2025-06-06",
    approvedDate: null,
    rejectedDate: null,
    rejectionReason: null,
    status: "pending",
    email: "renuka.d@email.com",
    businessType: "Family Farm",
    experience: "4 years",
    priority: "low",
    supplierId: null,
    route: null,
  },
  {
    id: 29,
    name: "Ajith Bandara",
    nic: "851234568V",
    phone: "+94 78 999 0000",
    location: "Horana, Western",
    supply: "520 kg",
    date: "2025-06-04",
    approvedDate: null,
    rejectedDate: null,
    rejectionReason: null,
    status: "pending",
    email: "ajith.b@email.com",
    businessType: "Individual Farmer",
    experience: "10 years",
    priority: "medium",
    supplierId: null,
    route: null,
  },
  {
    id: 30,
    name: "Nalaka Wijeratne",
    nic: "791234568V",
    phone: "+94 75 000 1111",
    location: "Panadura, Western",
    supply: "410 kg",
    date: "2025-06-02",
    approvedDate: null,
    rejectedDate: null,
    rejectionReason: null,
    status: "pending",
    email: "nalaka.w@email.com",
    businessType: "Cooperative",
    experience: "12 years",
    priority: "high",
    supplierId: null,
    route: null,
  },
  // Additional Rejected Suppliers (31-45)
  {
    id: 31,
    name: "Gamini Wickremasinghe",
    nic: "701234568V",
    phone: "+94 77 111 3333",
    location: "Tangalle, Southern",
    supply: "280 kg",
    date: "2025-05-28",
    approvedDate: null,
    rejectedDate: "2025-06-03",
    rejectionReason:
      "Inadequate land size and poor soil quality for tea cultivation.",
    status: "rejected",
    email: "gamini.w@email.com",
    businessType: "Individual Farmer",
    experience: "2 years",
    priority: "low",
    supplierId: null,
    route: null,
  },
  {
    id: 32,
    name: "Shirani Perera",
    nic: "811234568V",
    phone: "+94 76 222 4444",
    location: "Tissamaharama, Southern",
    supply: "190 kg",
    date: "2025-05-25",
    approvedDate: null,
    rejectedDate: "2025-06-01",
    rejectionReason:
      "Failed to meet minimum quality standards in sample testing.",
    status: "rejected",
    email: "shirani.p@email.com",
    businessType: "Family Farm",
    experience: "1 year",
    priority: "low",
    supplierId: null,
    route: null,
  },
  {
    id: 33,
    name: "Roshan Silva",
    nic: "721234568V",
    phone: "+94 78 333 5555",
    location: "Weligama, Southern",
    supply: "340 kg",
    date: "2025-05-22",
    approvedDate: null,
    rejectedDate: "2025-05-30",
    rejectionReason:
      "Distance from factory too far, transportation costs not viable.",
    status: "rejected",
    email: "roshan.s@email.com",
    businessType: "Individual Farmer",
    experience: "3 years",
    priority: "medium",
    supplierId: null,
    route: null,
  },
  {
    id: 34,
    name: "Deepika Jayawardena",
    nic: "861234568V",
    phone: "+94 75 444 6666",
    location: "Embilipitiya, Sabaragamuwa",
    supply: "250 kg",
    date: "2025-05-20",
    approvedDate: null,
    rejectedDate: "2025-05-28",
    rejectionReason: "Incomplete documentation and unverified land ownership.",
    status: "rejected",
    email: "deepika.j@email.com",
    businessType: "Individual Farmer",
    experience: "2 years",
    priority: "low",
    supplierId: null,
    route: null,
  },
  {
    id: 35,
    name: "Chandana Gunasekara",
    nic: "731234568V",
    phone: "+94 77 555 7777",
    location: "Balangoda, Sabaragamuwa",
    supply: "380 kg",
    date: "2025-05-18",
    approvedDate: null,
    rejectedDate: "2025-05-26",
    rejectionReason: "Tea plants not mature enough for commercial harvesting.",
    status: "rejected",
    email: "chandana.g@email.com",
    businessType: "Family Farm",
    experience: "1 year",
    priority: "low",
    supplierId: null,
    route: null,
  },
  // More Approved Suppliers (36-50)
  {
    id: 36,
    name: "Sunitha Rathnayake",
    nic: "651234567V",
    phone: "+94 76 666 8888",
    location: "Lindula, Central",
    supply: "690 kg",
    date: "2025-04-20",
    approvedDate: "2025-04-28",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "sunitha.r@email.com",
    businessType: "Cooperative",
    experience: "18 years",
    priority: "high",
    supplierId: "SUP-2025-036",
    route: "Route B-02 (Central Hills)",
  },
  {
    id: 37,
    name: "Upul Fernando",
    nic: "681234568V",
    phone: "+94 78 777 9999",
    location: "Ragala, Central",
    supply: "540 kg",
    date: "2025-04-18",
    approvedDate: "2025-04-26",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "upul.f@email.com",
    businessType: "Individual Farmer",
    experience: "14 years",
    priority: "medium",
    supplierId: "SUP-2025-037",
    route: "Route B-02 (Central Hills)",
  },
  {
    id: 38,
    name: "Mala Wickramasinghe",
    nic: "751234569V",
    phone: "+94 75 888 0000",
    location: "Deltota, Central",
    supply: "620 kg",
    date: "2025-04-15",
    approvedDate: "2025-04-23",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "mala.w@email.com",
    businessType: "Family Farm",
    experience: "16 years",
    priority: "high",
    supplierId: "SUP-2025-038",
    route: "Route A-01 (Colombo North)",
  },
  {
    id: 39,
    name: "Janaka Perera",
    nic: "821234569V",
    phone: "+94 77 999 1111",
    location: "Ella, Uva",
    supply: "470 kg",
    date: "2025-04-12",
    approvedDate: "2025-04-20",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "janaka.p@email.com",
    businessType: "Individual Farmer",
    experience: "11 years",
    priority: "medium",
    supplierId: "SUP-2025-039",
    route: "Route C-03 (Uva Province)",
  },
  {
    id: 40,
    name: "Wasana Silva",
    nic: "741234569V",
    phone: "+94 76 000 2222",
    location: "Passara, Uva",
    supply: "580 kg",
    date: "2025-04-10",
    approvedDate: "2025-04-18",
    rejectedDate: null,
    rejectionReason: null,
    status: "approved",
    email: "wasana.s@email.com",
    businessType: "Cooperative",
    experience: "13 years",
    priority: "high",
    supplierId: "SUP-2025-040",
    route: "Route C-03 (Uva Province)",
  },
];

// Utility functions for supplier operations
export const supplierUtils = {
  // Calculate dashboard metrics
  calculateMetrics: (suppliers) => {
    const total = suppliers.length;
    const pending = suppliers.filter((s) => s.status === "pending").length;
    const approved = suppliers.filter((s) => s.status === "approved").length;
    const rejected = suppliers.filter((s) => s.status === "rejected").length;
    const approvalRate = total > 0 ? Math.round((approved / total) * 100) : 0;
    const overdue = suppliers.filter((s) => {
      const requestDate = new Date(s.date);
      const daysDiff = Math.floor(
        (new Date() - requestDate) / (1000 * 60 * 60 * 24)
      );
      return s.status === "pending" && daysDiff > 3;
    }).length;

    return { total, pending, approved, rejected, approvalRate, overdue };
  },

  // Filter suppliers based on current view and filters
  filterSuppliers: (suppliers, filters, currentView) => {
    return suppliers.filter((s) => {
      // First filter by current view
      let matchesView = false;
      if (currentView === "approved") {
        matchesView = s.status === "approved";
      } else if (currentView === "pending") {
        matchesView = s.status === "pending";
      } else if (currentView === "rejected") {
        matchesView = s.status === "rejected";
      }

      if (!matchesView) return false;

      // Then apply search and other filters
      const matchesSearch =
        filters.search === "" ||
        s.name.toLowerCase().includes(filters.search.toLowerCase()) ||
        s.location.toLowerCase().includes(filters.search.toLowerCase()) ||
        (s.supplierId && s.supplierId.includes(filters.search)) ||
        ("SUP-2025-00" + s.id).includes(filters.search);
      const matchesStatus = !filters.status || s.status === filters.status;
      const matchesRegion =
        !filters.region || s.location.includes(filters.region);
      return matchesSearch && matchesStatus && matchesRegion;
    });
  },

  // Approve supplier
  approveSupplier: (suppliers, id, approvalData) => {
    return suppliers.map((s) =>
      s.id === id
        ? {
            ...s,
            status: "approved",
            approvedDate: new Date().toISOString().split("T")[0],
            supplierId: `SUP-2025-00${s.id}`,
            route: approvalData.route,
          }
        : s
    );
  },

  // Reject supplier
  rejectSupplier: (suppliers, id, reason) => {
    return suppliers.map((s) =>
      s.id === id
        ? {
            ...s,
            status: "rejected",
            rejectedDate: new Date().toISOString().split("T")[0],
            rejectionReason: reason,
          }
        : s
    );
  },
};
