// Sample route data
export const routes = [
  {
    id: "TR-001",
    routeName: "Galle-Akuressa Route",
    assignedDriver: "Pasindu Madushan",
    driverId: "D001",
    supplierCount: 12,
    estimatedLoad: 350,
    actualLoad: 342,
    bagCounts: 28,
    region: "Southern Province",
    status: "Active",
    createdDate: "2024-01-15",
    lastUpdated: "2024-06-15",
    distance: 45.8,
    estimatedTime: "3.5 hours",
    startLocation: { name: "Galle", lat: 6.0328, lng: 80.2167 },
    endLocation: { name: "Akuressa", lat: 6.1, lng: 80.4833 },
  },
  {
    id: "TR-002",
    routeName: "Matara-Deniyaya Circuit",
    assignedDriver: null,
    driverId: null,
    supplierCount: 8,
    estimatedLoad: 280,
    actualLoad: 0,
    bagCounts: 0,
    region: "Southern Province",
    status: "Inactive",
    createdDate: "2024-02-20",
    lastUpdated: "2024-06-10",
    distance: 38.2,
    estimatedTime: "3 hours",
    startLocation: { name: "Matara", lat: 5.9496, lng: 80.5469 },
    endLocation: { name: "Deniyaya", lat: 6.341, lng: 80.5572 },
  },
  {
    id: "TR-003",
    routeName: "Kandy Hills Route",
    assignedDriver: "Chaminda Fernando",
    driverId: "D002",
    supplierCount: 15,
    estimatedLoad: 420,
    actualLoad: 405,
    bagCounts: 32,
    region: "Central Province",
    status: "Active",
    createdDate: "2024-01-08",
    lastUpdated: "2024-06-20",
    distance: 52.3,
    estimatedTime: "4 hours",
    startLocation: { name: "Kandy", lat: 7.2906, lng: 80.6337 },
    endLocation: { name: "Hanthana", lat: 7.2639, lng: 80.6422 },
  },
  {
    id: "TR-004",
    routeName: "Nuwara Eliya Express",
    assignedDriver: "Nimal Silva",
    driverId: "D003",
    supplierCount: 10,
    estimatedLoad: 320,
    actualLoad: 298,
    bagCounts: 25,
    region: "Central Province",
    status: "Active",
    createdDate: "2024-03-12",
    lastUpdated: "2024-06-18",
    distance: 41.5,
    estimatedTime: "3.2 hours",
    startLocation: { name: "Nuwara Eliya", lat: 6.9704, lng: 80.7891 },
    endLocation: { name: "Hatton", lat: 6.8916, lng: 80.5975 },
  },
];

// Sample suppliers assigned to routes
export const routeSuppliers = {
  "TR-001": [
    {
      id: "S001",
      name: "Kumara Tea Estate",
      location: "Galle",
      expectedLoad: 45,
      actualLoad: 42,
      lastMonthWeight: 44,
      bagCount: 4,
      contactPerson: "Kumara Perera",
      phone: "077-1234567",
    },
    {
      id: "S002",
      name: "Silva Gardens",
      location: "Akuressa",
      expectedLoad: 38,
      actualLoad: 35,
      lastMonthWeight: 37,
      bagCount: 3,
      contactPerson: "Silva Fernando",
      phone: "077-2345678",
    },
    {
      id: "S003",
      name: "Green Valley Tea",
      location: "Elpitiya",
      expectedLoad: 52,
      actualLoad: 48,
      lastMonthWeight: 50,
      bagCount: 5,
      contactPerson: "Rohan Jayasinghe",
      phone: "077-3456789",
    },
  ],
  "TR-003": [
    {
      id: "S004",
      name: "Highland Tea Co",
      location: "Kandy",
      expectedLoad: 65,
      actualLoad: 62,
      lastMonthWeight: 64,
      bagCount: 6,
      contactPerson: "Mahinda Rajapaksa",
      phone: "077-4567890",
    },
    {
      id: "S005",
      name: "Mountain View Estate",
      location: "Peradeniya",
      expectedLoad: 55,
      actualLoad: 53,
      lastMonthWeight: 54,
      bagCount: 5,
      contactPerson: "Sunil Bandara",
      phone: "077-5678901",
    },
  ],
  "TR-004": [
    {
      id: "S006",
      name: "Alpine Tea Gardens",
      location: "Nuwara Eliya",
      expectedLoad: 75,
      actualLoad: 70,
      lastMonthWeight: 72,
      bagCount: 7,
      contactPerson: "Chandra Wickrama",
      phone: "077-6789012",
    },
  ],
};

// Available drivers
export const availableDrivers = [
  {
    id: "D001",
    name: "Pasindu Madushan",
    phone: "077-1111111",
    licenseClass: "Heavy Vehicle",
  },
  {
    id: "D002",
    name: "Chaminda Fernando",
    phone: "077-2222222",
    licenseClass: "Heavy Vehicle",
  },
  {
    id: "D003",
    name: "Nimal Silva",
    phone: "077-3333333",
    licenseClass: "Heavy Vehicle",
  },
  {
    id: "D004",
    name: "Kamal Perera",
    phone: "077-4444444",
    licenseClass: "Heavy Vehicle",
  },
  {
    id: "D005",
    name: "Saman Gunawardena",
    phone: "077-5555555",
    licenseClass: "Heavy Vehicle",
  },
];

// Regions
export const regions = [
  "Western Province",
  "Central Province",
  "Southern Province",
  "Northern Province",
  "Eastern Province",
  "North Western Province",
  "North Central Province",
  "Uva Province",
  "Sabaragamuwa Province",
];

// Route status options
export const routeStatuses = [
  "Active",
  "Inactive",
  "Under Maintenance",
  "Suspended",
];
